sudo: required
language: node_js
node_js:
- '8'
services:
- docker
- mongodb
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    tags: true
env:
  global:
  - secure: efe4HC1pOpMzO/HND1GGyo0aNa6oZfARYWAfp8hvYprsNkrx0xkQiu9mnaCto/KgYB4IVc3r/b+nIg5BdToXpaBWqFjVVEP22U6ewM9uxwwQ54zHX0Obl7+xG0oHsFDo4H5KweG/gyBZLy3HS/PtoZ7ykGB9mFeasdnqvNkF+O0=
  - secure: hCrLavB/xD8KvuUWkAk1wBVjCuyd6Tqzf5I40LNpvbxKPW9QIqZyg1pxwruXAabqjwynuGO5+QTViFEHejPP48uErJvl3kHlgZ0H9XHEFeceEhFPi2mDNqhxnfWjKFCS+HOrRvi18Szz+KqzZFaiJ5MRGqN3VgSJb0u/6Fk/zvQ=
  - secure: g0573EIIWNRwTUsLO73v4ctZ7V3HCfxwJ8QoiitYmFz8VKAw0vJCj2akcKjWqC1aV0DCz3lAiY3a3s5JXjLYHwLAXK9J9PjQ94tUx2EOwU4bmeqb/7pTvLXrPDdkiQv08lrQEgzOT2pLz1Z/oM8mVN7TIPwWvnoQ/pm3qchYKC4=
